export const TRUTH = {
    DEFAULT_FREQUENCY: 1.0,
    DEFAULT_CONFIDENCE: 0.9,
    WEAKENING_FACTOR: 1.0,
    PRECISION: 2,
    EPSILON: 1e-10,
    MIN_PRIORITY: 0.0,
    MAX_PRIORITY: 1.0,
};

export const PRIORITY = {
    DEFAULT: 0.5,
};